### ISSUE TITLE
[Feature] Alerts for the compaction job metrics

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-druid#603]
**Feature (What you would like to be added):**
We are exposing metrics for compaction job in ETCD druid by #569 . Now we need to whitelist the metrics in g/g  and raise correct alerts based on the metrics. We have decided to raise alerts when `job_duration_seconds` and `jobs_total` with failed labels cross certain thresholds.
**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**
Threshold for `jobs_total` with failed label in a seed : 10% of aggregated `jobs_total` (This alert would be raised per seed)
Threshold for `jobs_total` with failed label in a shoot:  10% of `jobs_total`(This alert would be raised per shoot)

To raise the alert at seed level,  [Aggregate prometheus](https://github.com/gardener/gardener/tree/master/docs/monitoring#aggregate-prometheus) can be used. The metrics `jobs_total` with failed label is scraped by [cache prometheus](https://github.com/gardener/gardener/tree/master/docs/monitoring#prometheus) from etcd-druid. Aggregate prometheus can aggregate metrics `jobs_total` from cache prometheus. Seed level alerts can be raised on this aggregated metrics from aggregated prometheus. 

To raise the alert at shoot level, alerts can be raised in control plane prometheus. Control plane prometheus already federate shoot specific `jobs_total` from cache prometheus. So, to raise the alert for `jobs_total` at shoot level, we need to add an alert for `jobs_total` in  [here](https://github.com/gardener/gardener/blob/72ce85574d37e3a8ffcf2b082aca643f87059ed8/pkg/component/etcd/monitoring.go#L94)

Another idea is that we aggregate the alert data that is already raised on shoot control plane prometheus. Alerts from the shoot control plane prometheus are passed to aggregate prometheus in garden namespace. These are just alert data. We can aggregate these alert data streaming from multiple shoots to aggregate prometheus and send alert for `jobs_total` at seed level.

**Comment by DelinaDeng** [comment]
We received many alerts in gardener AC canary landscape which says "Pod 60f2a9-compact-job-cb9tv is not ready for more than 30 minutes". 

Is it related to this issue?

**Comment by abdasgupta** [comment]
@DelinaDeng It shouldn't be related to this issue. The issue you mentioned seems due to pods not running the container at all due to unavailability of resources or scheduling problem. We can check farther if you give us the cluster details

**Comment by abdasgupta** [comment]
As an out of band discussion with @shreyas-s-rao , we decided to consider `jobs_total` as metrics to raise alert upon crossing a threshold both for shoots and seeds.

**Comment by abdasgupta** [comment]
As per an out-of-band discussion with @shreyas-s-rao , we decided to use `jobs_total` with failed label for raising alerts for both on shoot and seed.

**Comment by renormalize** [comment]
After more discussion, it was decided that raising an alert for every compaction job's failure would cause a very large number of alerts to be raised, since the job could fail for a multitude of reasons.

To get a more holistic understanding of the health of the shoots in the seed, alerts are to be raised at a seed level when more than X% (for example, 10%) of the compaction jobs deployed in the seed fail.

It would only make sense to raise alerts for compaction jobs deployed for a shoot, if that particular job fails more than a particular number of times in succession. Setting a particular percentage limit for alerts to be raised on `jobs_total` would not really be meaningful. If the latest job succeeds, there is no need to raise an alert. Setting a percentage after which alerts are triggered for the shoot would not consider the status of the latest job.

Behavior of compaction jobs that are deployed in a live setting could be used to come up with a limit, after which alerts are raised for a shoot.
