### ISSUE TITLE
[Feature] Bump Gardener dependency 

### ISSUE THREAD

**Issue by afritzler** [gardener/etcd-druid#734]
**Feature (What you would like to be added):**

Currently the `etcd-druid` project is using a pretty old Gardener dependency (`v1.76.0`). Is that intended or can the Gardener version be bumped to a post 1.8x version?

**Comment by shreyas-s-rao** [comment]
g/g version was bumped 4 months ago, and the latest version at the time was `1.76.0`. We have no issues bumping it to `1.85.0` (current latest version). I'll raise a PR for the same

**Comment by shreyas-s-rao** [comment]
@afritzler can the fix for this wait for a few more days? There seems to be an issue with the e2e tests for https://github.com/gardener/etcd-druid/pull/748, and we will need some time to dig into this and fix it. In the meantime, there are other tasks which require my attention in the next week, hence asking if this PR can be delayed till then.

**Comment by afritzler** [comment]
All good, we are not in a rush here.
