### ISSUE TITLE
Add a new configurable field `fullSnapshotLeaseUpdateInterval` in spec.backup section of Etcd CR

### ISSUE THREAD

**Issue by anveshreddy18** [gardener/etcd-druid#763]
**Feature (What you would like to be added):**

Add `fullSnapshotLeaseUpdateInterval` field to the spec.backup section of Etcd yaml.

**Motivation (Why is this needed?):**
* The backup-restore [PR#711](https://github.com/gardener/etcd-backup-restore/pull/711) introduces a new flag `full-snapshot-lease-update-interval` to configure the retry interval for updating the full snapshot lease. Adding this new `fullSnapshotLeaseUpdateInterval` field to Etcd CR allows user to control the behaviour of retrying to update full snapshot lease 

Note: It will be an optional field, and when not set, backup-restore takes care of setting a default value to it.

**Approach/Hint to the implement solution (optional):**

Add the `fullSnapshotLeaseUpdateInterval` field to the spec.backup section of Etcd yaml, and define the `FullSnapshotLeaseUpdateInterval` field in the BackupSpec struct of Etcd CRD

**Comment by shreyas-s-rao** [comment]
Thanks for creating the issue @anveshreddy18 . I would recommend calling the field `FullSnapshotLeaseUpdateInterval`. 
1. Snapshot is a fully qualified word and needs to be capitalised. It doesn't help much to use its short form `snap`
2. The word `retry` means that if a lease update failed, then the operation is retried after a certain interval. In the updation logic in https://github.com/gardener/etcd-backup-restore/pull/711, you are anyway trying an update of the full snapshot lease every X minutes (defined by the interval), irrespective of whether the previous updation succeeded or failed. So this isn't really a "retry", but simply a periodic "try"

Please also consider making these changes in the etcdbr PR as well, since the same points apply to that too. Thanks!

**Comment by anveshreddy18** [comment]
> Thanks for creating the issue @anveshreddy18 . I would recommend calling the field `FullSnapshotLeaseUpdateInterval`.
> 
> 1. Snapshot is a fully qualified word and needs to be capitalised. It doesn't help much to use its short form `snap`
> 2. The word `retry` means that if a lease update failed, then the operation is retried after a certain interval. In the updation logic in [Full snapshot lease update retry on failure etcd-backup-restore#711](https://github.com/gardener/etcd-backup-restore/pull/711), you are anyway trying an update of the full snapshot lease every X minutes (defined by the interval), irrespective of whether the previous updation succeeded or failed. So this isn't really a "retry", but simply a periodic "try"
> 
> Please also consider making these changes in the etcdbr PR as well, since the same points apply to that too. Thanks!

Thanks for the suggestion @shreyas-s-rao, updated the issue, druid PR and etcdbr PR as well.
