### ISSUE TITLE
[BUG] Etcd failed to flush changes from WAL to the DB before shutting down/crashing.

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#99]
**Describe the bug:**
After a single-node etcd instance provisioned via `etcd-druid` terminated abnormally (non-zero exit code) the `etcd` container restarted and the the `backup-restore` sidecar container (on data directory verification) had the following logs.

```
current etcd revision (2314180238) is less than latest snapshot revision (2314180239): possible data loss
```

On circumventing the backup restoration triggered because of this, it was found that the WAL directory (not checked by the `backup-restore sidecar) contained more recent revisions which were applied after the restart (without the backup restoration).

**Expected behavior:**
`etcd-druid` should try and configure etcd instances to shut down safely (and flush the WAL changes to the database) or often that.

**How To Reproduce (as minimally and precisely as possible):**
Not known yet.

**Logs:**
```
current etcd revision (2314180238) is less than latest snapshot revision (2314180239): possible data loss
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by ishan16696** [comment]
This issue when single node etcd fails to flush changes from WAL to the DB before shuttingDown/crashing has been fixed by this PR: https://github.com/gardener/etcd-backup-restore/pull/275 on etcd-backup-restore.
so, IMO for single-node etcd cluster etcd-druid don't have to take any action to fix this as it is now handled by etcd-backup-restore itself.
I'm closing this issue as action is required from druid side.
/close
